spring:
  datasource:
    url: jdbc:mysql://taba-mysql.cr2i4c66apzs.ap-northeast-2.rds.amazonaws.com:3306/taba?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: cks54960323*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
oauth:
  kakao:
    client-id: 0597ae87f8af7857bdf50b83f958631b
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: WI8hCJJUnu
    client-id: FmlggPFTyUJ9RTE4KSHw
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
# jwt secret key
jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
